Controllers/AdminLibraryController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using mis_mmc.Models;

namespace mis_mmc.Controllers;

public class AdminLibraryController : Controller
{
    private readonly DataContext _context;

    public AdminLibraryController(DataContext context)
    {
        _context = context;
       
    }
    public int Getid ()

    {

        Random r = new Random();
    
        return r.Next(10000,99999);
    
    }
    // GET
    public IActionResult Index()
    {
        var data = _context.BookModels.ToList();
        ViewBag.data = data;
        return View();
        
    }
    public IActionResult AddBook()
    {
        var data = _context.ProgramModels.ToList();
        ViewBag.data = data;
        ViewData["Program"] = new SelectList(_context.Set<ProgramModel>(), "s_no", "name");

        return View();
    }
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> AddBook(BookModel bookModel)
    {


        _context.BookModels.Add(bookModel);
        _context.SaveChanges();
        return RedirectToAction("Index");

    }
    public IActionResult UpdateBook()
    {
        return View();
    }
    public IActionResult IssueBook()
    {
        var data = _context.StudentModels.ToList();
        ViewBag.data = data;
        var book = _context.BookModels.ToList();
        ViewBag.book = book;
      
        return View();
    }
    
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> IssueBook(string student, string book, string expiry_date, string uid)
    {
        string sid = _context.StudentModels.Where(x => x.email.Equals(student)).First().s_no.ToString();
        string bid = _context.BookModels.Where(x => x.name.Equals(book)).First().s_no.ToString();
        
        var bk = _context.BookModels.Where(p => p.s_no.ToString() == bid).FirstOrDefault();
        bk.is_issued=true;
        bk.stock-=1;
       
        BookIssueModel issue = new BookIssueModel()
        {
            sid = int.Parse(sid),
            bid=int.Parse(bid),
            issued_date = DateOnly.FromDateTime(DateTime.Now),
            uid=uid, 
            expiry_date=DateOnly.Parse(expiry_date),
            is_returned=false


        };
         _context.BookIssueModels.Add(issue);
        
        await _context.SaveChangesAsync();
        return RedirectToAction(("Index"));
    }
    public IActionResult IssueDetails()
    {
        var data = _context.BookIssueModels.Include(f=>f.BookModel).Include(f=>f.StudentModel).ToList();
        ViewBag.data = data;
        return View();
    }

    public IActionResult IssueStudents(int id)
    {
         var data = _context.BookIssueModels.Include(f=>f.BookModel).Include(f=>f.StudentModel).Where(x => x.bid.Equals(id)).ToList();
                ViewBag.data = data;
        return View();
    }

    public IActionResult ConfirmReturn(int id)
    {
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> ConfirmReturn(int id, string return_date)
    {
        var isuue = _context.BookIssueModels.Include(f=>f.BookModel).Where(f => f.s_no==id).FirstOrDefault();
        isuue.is_returned = true;
        isuue.return_date=DateOnly.Parse(return_date);
        isuue.BookModel.stock -= 1;
        
        await _context.SaveChangesAsync();
        return RedirectToAction ("IssueDetails");
    }
}

Views/AdminLibrary/AddBook.cshtml
@{
    ViewData["Title"] = "Home Page";
    Layout = "_Layout_librarian";

}
@model mis_mmc.Models.BookModel

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Add Books</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item">
                        <a href="#">Admin</a>
                    </li>
                     <li class="breadcrumb-item "> Library</li>
                    <li class="breadcrumb-item active"> Add Books</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>
<section class="content">
    <div class="container-fluid">

        <div class="row">
            <div class="col-12">
               <div class="card">
                         <div class="card-body">
                         <div class="card-title">Books Form</div>
                         <hr>
                         <form asp-action="AddBook">
                           
                             
                             <div class="form-group">
                                 <label for="input-3">Book Name</label>
                                 <input type="text" class="form-control" id="input-3" placeholder="Enter Name" name="name" required>
                             </div>
                             <div class="form-group">
                                 <label for="input-4">Author(s)</label>
                                 <input type="text" class="form-control" id="input-4" placeholder="Enter name of author" name="author" required>
                             </div>
                             <div class="form-group">
                                 <label for="input-5">Publication</label>
                                 <input type="text" class="form-control" id="input-5" placeholder="Enter name of publication" name="publication" required>
                             </div>
                             <div class="form-group">
                                 <label for="input-11">Current Stock</label>
                                 <input type="number" class="form-control" id="input-11" placeholder="Enter stock" name="stock" required>
                             </div>
                             <div class="form-group">
                                 <label for="input-6">Type</label>
                                 <select class="form-control" id="input-6"  name="type" required list="system">
                                     <datalist id="system">
                                         <option value="general"  > General </option>
                                         <option value="program"> Program Related</option>
                                     </datalist>
                                 </select>
                             </div>
                             
                             <div class="form-group">
                                 <label asp-for="pid" class="control-label">Program</label>
                                 <select asp-for="pid" id="select"  class ="form-control" asp-items="ViewBag.Program" disabled="disabled"></select>
                             </div>
                             <div class="form-group">
                                 <label for="input-2">Semester/year</label>
                                 
                                 <input type="number" class="form-control" id="input-2" placeholder="Enter semester/year" name="sem_year" required max="8" disabled="disabled" >
                                
                             </div>
                             






                             <button type="submit" class="btn btn-light px-5"> Add</button>
                              <script type="text/javascript">
                              
                              document.querySelector("#input-6").addEventListener("input",function (){
                                  if (document.getElementById("input-6").value == "general"){
                                     
                                      document.querySelector("#select").setAttribute("disabled","disabled");
                                      document.querySelector("#input-2").setAttribute("disabled","disabled");
                                      
                                      
                                      
                                  }
                                  else  {
                                      
                                      document.querySelector("#select").removeAttribute("disabled");
                                      document.querySelector("#input-2").removeAttribute("disabled");
                                 
                                 }
                                  })
                              
                              
                          
                                                             
                                                              </script>
                             
                         </form>
                         
                        
                       </div>
                       </div>
                    </div>

                <!-- /.card -->


                <!-- /.card-header -->

                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
   

    <!-- /.container-fluid -->
</section>

Views/AdminLibrary/ConfirmReturn.cshtml
@{
    ViewData["Title"] = "Home Page";
    Layout = "_Layout_librarian";

}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Return Book</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item">
                        <a href="#">Admin</a>
                    </li>
                     <li class="breadcrumb-item "> Library</li>
                    <li class="breadcrumb-item active"> Confirm return</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>
<section class="content">
    <div class="container-fluid">

        <div class="row">
            <div class="col-12">
               <div class="card">
                         <div class="card-body">
                         <div class="card-title">Book Issue Form</div>
                         <hr>
                          <form method="post" >
                              
                             
                              
                              <div class="form-group">
                                  <label for="input-2">Return date </label>
                                  <input type="date" class="form-control" id="input-2" placeholder="Enter Name" name="return_date" required>
                                                                
                              </div>
                             
                              
                              
                        
                              <div class="form-group">
                          <button type="submit" class="btn btn-light px-5"> Issue</button>
                        </div>
                        </form>
                       </div>
                       </div>
                    </div>

                <!-- /.card -->


                <!-- /.card-header -->

                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
   

    <!-- /.container-fluid -->
</section>

Views/AdminLibrary/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
    Layout = "_Layout_librarian";

}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Library</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item">
                        <a href="#">Admin</a>
                    </li>
                    <li class="breadcrumb-item active"> Library</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>
<section class="content">
    <div class="container-fluid">

        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                       
                        <form class="search-bar" style="float: left; ">
                            <input type="text" class="form-control" placeholder="Enter keywords" style="float: left">
                            <a href="">
                                <i class="icon-magnifier"></i>
                            </a>
                        </form>
                        <a style="margin-left: 20px;" asp-controller="AdminLibrary" asp-action="AddBook" >
                            <button type="button" class="btn btn-primary">Add new</button>
                        </a>
                        <a style="margin-left: 20px;" asp-controller="AdminLibrary" asp-action="IssueBook">
                            <button type="button" class="btn btn-primary">Issue book</button>
                        </a>
                        <a style="margin-left: 20px;" asp-controller="AdminLibrary" asp-action="IssueDetails">
                            <button type="button" class="btn btn-primary">Issue details</button>
                        </a>
                        

                    </div>
                   


                    <!-- /.card-header -->
                    <div class="card-body">
                       
                        <table id="example2" class="table table-bordered table-hover table-responsive">
                            <thead>
                            <tr>
                                <th>S.No</th>
                                <th>Book name</th>
                                <th>Author(s)</th>
                                <th>Publication</th>
                                <th>Current Stock</th>
                                <th>Is_issued</th>
                                <th>Action</th>
                                
                            </tr>
                            </thead>
                            <tbody>

  @{
                                   int i = 1;
                               }
                            
                            @foreach (var item in ViewBag.data)

                            {
                                <tr>
                                    <td>@i</td>
                                    <td>@item.name</td>
                                    <td>@item.author</td>
                                    <td>@item.publication</td>
                                    <td>@item.stock</td>
                                    <td>@item.is_issued</td>


                                    <td>
                                        @if (item.is_issued == true)
                                        {
                                            <a asp-controller="AdminLibrary" asp-action="IssueStudents" asp-route-id="@item.s_no">
                                                <button  type="button" class="btn btn-info"> Issue Info</button>
                                            </a>
                                                                                
                                        }
                                
                                        <a asp-controller="AdminLibrary" asp-action="UpdateBook">
                                            <button style="width: 70px;" type="button" class="btn btn-info">Edit</button>
                                        </a>
                                        <a onclick="return confirm('Are you sure want to delete? ')">
                                            <button type="button" class="btn btn-danger">Delete</button>
                                        </a>
                                    </td>
                                </tr>
                                i++;
                            }
                            </tbody>

                        </table>
                    </div>

                    <!-- /.card-body -->
                </div>
                <!-- /.card -->


                <!-- /.card-header -->

                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </div>


    <!-- /.container-fluid -->
</section>

Views/AdminLibrary/IssueBook.cshtml
@{
    ViewData["Title"] = "Home Page";
    Layout = "_Layout_librarian";

}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Issue Book</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item">
                        <a href="#">Admin</a>
                    </li>
                     <li class="breadcrumb-item "> Library</li>
                    <li class="breadcrumb-item active"> Issue Book</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>
<section class="content">
    <div class="container-fluid">

        <div class="row">
            <div class="col-12">
               <div class="card">
                         <div class="card-body">
                         <div class="card-title">Book Issue Form</div>
                         <hr>
                          <form method="post" >
                              <div class="form-group">
                                  <label for="input-1">Input student email</label>
                                  <input type="text" class="form-control" id="input-1" placeholder="Enter Name" name="student" required list="student">
                                  <datalist id="student">
                                      @foreach (var item in ViewBag.data){
                                          <option value="@item.email"/>  
                                          
                                            
                                          }
                                  </datalist>
                              </div>
                              <div class="form-group">
                                  <label for="input-2"> Name of Book</label>
                                  <input type="text" class="form-control" id="input-2" placeholder="Enter Name" name="book" required list="program">
                                  <datalist id="program">
                                      @foreach (var item in ViewBag.book){
                                                                               <option value="@item.name"/>  
                                                                               
                                                                                 
                                                                               }
                                  </datalist>
                              </div>
                              
                              <div class="form-group">
                                  <label for="input-2">Expiry date</label>
                                  <input type="date" class="form-control" id="input-2" placeholder="Enter Name" name="expiry_date" required>
                                                                
                              </div>
                              <div class="form-group">
                                  <label for="input-3">Input Unique Book Id</label>
                                  <input type="text" class="form-control" id="input-2" placeholder="Enter Name" name="uid" required>
                                                                                              
                              </div>
                              
                              
                        
                              <div class="form-group">
                          <button type="submit" class="btn btn-light px-5"> Issue</button>
                        </div>
                        </form>
                       </div>
                       </div>
                    </div>

                <!-- /.card -->


                <!-- /.card-header -->

                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
   

    <!-- /.container-fluid -->
</section>

Views/AdminLibrary/IssueDetails.cshtml
@{
    ViewData["Title"] = "Home Page";
    Layout = "_Layout_librarian";

}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Issue Details</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item">
                        <a href="#">Admin</a>
                    </li>
                    <li class="breadcrumb-item "> Library</li>
                    <li class="breadcrumb-item active"> Issue Details</li>
                    
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>
<section class="content">
    <div class="container-fluid">

        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                       
                        <form class="search-bar" style="float: left; ">
                            <input type="text" class="form-control" placeholder="Enter keywords" style="float: left">
                            <a href="">
                                <i class="icon-magnifier"></i>
                            </a>
                        </form>
                       

                    </div>
                   


                    <!-- /.card-header -->
                    <div class="card-body">
                       
                        <table id="example2" class="table table-bordered table-hover table-responsive">
                            <thead>
                            <tr>
                                <th>S.No</th>
                                <th>Book name</th>
                                <th>Book id</th>
                                <th>Student name</th>
                                <th>Student id</th>
                                <th>Issue Date</th>
                                <th>Expiry Date</th>
                                <th>Is_returned</th>
                                <th>Return Date</th>
                                <th>Action</th>
                                <th></th>
                                
                            </tr>
                            </thead>
                            <tbody>

  @{
                                   int i = 1;
                               }
                            
                            @foreach (var item in ViewBag.data)

                            {
                                <tr>
                                    <td>@i</td>
                                    <td>@item.BookModel.name</td>
                                    <td>@item.uid</td>
                                    <td>@item.StudentModel.name</td>
                                    <td>@item.StudentModel.uid</td>
                                    <td>@item.issued_date</td>
                                    <td>@item.expiry_date</td>
                                    <td>@item.is_returned</td>
                                    <td>@item.return_date</td>


                                    <td>
                                           @if (item.is_returned != true)
                                           {



                                               <a asp-controller="AdminLibrary" asp-action="ConfirmReturn" asp-route-id="@item.s_no">
                                                   <button  type="button" class="btn btn-info">Confirm Return</button>
                                               </a>
                                           }

                                    </td>
                                </tr>
                                i++;
                            }
                            </tbody>

                        </table>
                    </div>

                    <!-- /.card-body -->
                </div>
                <!-- /.card -->


                <!-- /.card-header -->

                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </div>


    <!-- /.container-fluid -->
</section>

Views/AdminLibrary/IssueStudents.cshtml
@{
    ViewData["Title"] = "Home Page";
    Layout = "_Layout_librarian";

}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Issue Details</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item">
                        <a href="#">Admin</a>
                    </li>
                    <li class="breadcrumb-item "> Library</li>
                    <li class="breadcrumb-item active"> Issue Details</li>
                    
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>
<section class="content">
    <div class="container-fluid">

        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                       
                        <form class="search-bar" style="float: left; ">
                            <input type="text" class="form-control" placeholder="Enter keywords" style="float: left">
                            <a href="">
                                <i class="icon-magnifier"></i>
                            </a>
                        </form>
                       

                    </div>
                   


                    <!-- /.card-header -->
                    <div class="card-body">
                        <h5>This book is currently issued by following students:</h5>

                        <table id="example2" class="table table-bordered table-hover table-responsive">
                            <thead>
                            <tr>
                                <td>S.No</td>
                                <th>Student Name</th>
                                <th>Student id</th>
                                <th>Unique Bookid</th>
                                <th>Issued date</th>
                                <th>Expiry Date</th>
                                <th>Is_returned</th>
                                <th>Return Date</th>
                                <th>Action</th>
                                <th></th>

                            </tr>
                            </thead>
                            <tbody>

                            @{
                                int i = 1;
                            }

                            @foreach (var item in ViewBag.data)

                            {
                                <tr>
                                    <td>@i</td>
                                    <td>@item.StudentModel.name</td>
                                    <td>@item.StudentModel.uid</td>
                                    <td>@item.uid</td>
                                    <td>@item.issued_date</td>
                                    <td>@item.expiry_date</td>
                                    <td>@item.is_returned</td>
                                    <td>@item.return_date</td>


                                    <td>

   @if (item.is_returned != true)
   {
       
       <a asp-controller="AdminLibrary" asp-action="ConfirmReturn" asp-route-id="@item.s_no">
           <button style="width: 70px;" type="button" class="btn btn-info">Confirm Return</button>
       </a>
   }

                                    </td>
                                </tr>
                                i++;
                            }
                            </tbody>

                        </table>
                    </div>

                    <!-- /.card-body -->
                </div>
                <!-- /.card -->


                <!-- /.card-header -->

                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </div>


    <!-- /.container-fluid -->
</section>

Views/AdminLibrary/UpdateBook.cshtml
@{
    ViewData["Title"] = "Home Page";
    Layout = "_Layout_librarian";

}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Add Books</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item">
                        <a href="#">Admin</a>
                    </li>
                     <li class="breadcrumb-item "> Library</li>
                    <li class="breadcrumb-item active"> Update Books</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>
<section class="content">
    <div class="container-fluid">

        <div class="row">
            <div class="col-12">
               <div class="card">
                         <div class="card-body">
                         <div class="card-title">Update Books Form</div>
                         <hr>
                         <form>
                           
                             
                             <div class="form-group">
                                 <label for="input-3">Book Name</label>
                                 <input type="text" class="form-control" id="input-3" placeholder="Enter Name" name="name" required>
                             </div>
                             <div class="form-group">
                                 <label for="input-4">Author(s)</label>
                                 <input type="text" class="form-control" id="input-4" placeholder="Enter name of author" name="author" required>
                             </div>
                             <div class="form-group">
                                 <label for="input-11">Current Stock</label>
                                 <input type="number" class="form-control" id="input-11" placeholder="Enter stock" name="stock" required>
                             </div>
                           
                                
                                
                     
                                 
                                 
                                 <button type="submit" class="btn btn-light px-5"> Update</button>
                             
                         </form>
                       </div>
                       </div>
                    </div>

                <!-- /.card -->


                <!-- /.card-header -->

                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
   

    <!-- /.container-fluid -->
</section>