Controllers/TeacherAssignmentController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using mis_mmc.Models;

namespace mis_mmc.Controllers;

public class TeacherAssignmentController : Controller
{
    private readonly DataContext _context;
    private readonly IWebHostEnvironment _webHostEnvironment;
    public TeacherAssignmentController(DataContext context, IWebHostEnvironment webHostEnvironment)
    {
        _context = context;
        _webHostEnvironment = webHostEnvironment;
    }
    public async Task<string> UploadImage(string folderpath, IFormFile file)
    {
        folderpath += file.FileName;
        string serverFolder = Path.Combine(_webHostEnvironment.WebRootPath, folderpath);
        await file.CopyToAsync(new FileStream(serverFolder, FileMode.Create));
        return "/" + folderpath;
    }// GET
    public IActionResult Index(int id)
    {
        ViewBag.data = _context.AssignmentModels.Include(c => c.CourseModel).Include(c => c.TeacherModel)
            .Where(x => x.tid.Equals(id)).OrderBy(x => x.published_date);
        ViewData["Course"] = new SelectList(_context.Set<CourseModel>().Where(c=>c.tid.Equals(id)), "s_no", "name");

         return View();

    }
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Index(int id, AssignmentModel assignmentModel, IFormFile file, string due_date )

    {
        string folder = "file/";
        assignmentModel.tid = id;
        assignmentModel.published_date = DateOnly.FromDateTime(DateTime.Today);
        assignmentModel.due_date = DateOnly.Parse(due_date);
        assignmentModel.file = await UploadImage(folder, file);
        _context.AssignmentModels.Add(assignmentModel);
        _context.SaveChanges();
        return RedirectToAction("Index");
        

    }
}

Views/TeacherAssignment/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
    Layout = "_Layout_teacher";

}
 @model mis_mmc.Models.AssignmentModel
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Assignments</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item">
                        <a href="#">Teacher</a>
                    </li>
                    
                    <li class="breadcrumb-item active"> Assignments</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>
<section class="content">
    <div class="container-fluid">

        <div class="row">
            <div class="col-12">
               <div class="card">
                         <div class="card-body">
                         <div class="card-title">Publish New Assignment</div>
                         <hr>
                         <form method="post" asp-controller="TeacherAssignment" asp-action="Index"enctype="multipart/form-data" >
                             <div class="form-group">
                                 <label asp-for="cid" class="control-label">Select Course</label>
                                 <select asp-for="cid" class ="form-control" asp-items="ViewBag.course"></select>
                             </div>
                             


                               
                             <div class="form-group">
                                 <label for="input-3">Name</label>
                                 <input type="text" class="form-control" id="input-3" placeholder="Enter Name" name="name" required>
                             </div>
                             <div class="form-group">
                                 <label for="input-4">Description</label>
                                 <input type="text" class="form-control" id="input-4" placeholder="Enter Description" name="description" required>
                             </div>
                             <div class="form-group">
                                 <label for="input-5">File</label>
                                 <input type="file" class="form-control" id="input-5" name="file">
                             </div>
                              <div class="form-group">
                                  <label for="input-8">Total Points</label>
                                  <input type="number" class="form-control" id="input-8" name="points">
                                  </div>
                              <div class="form-group">
                                  <label for="input-6">Due date</label>
                                  <input type="date" class="form-control" id="input-6" placeholder="Enter Description" name="due_date" required>
                                  </div>

                             <button type="submit" class="btn btn-light px-5"> Publish</button>

                         </form>
                       </div>
                       </div>
                    </div>

                <!-- /.card -->


                <!-- /.card-header -->

                <div class="card">
                    <h1>Previous Assignments</h1>
                    <div class="card-header">

                        <form class="search-bar" style="float: left; ">
                            <input type="text" class="form-control" placeholder="Enter keywords" style="float: left">
                            <a href="">
                                <i class="icon-magnifier"></i>
                            </a>
                        </form>


                    </div>



                    <!-- /.card-header -->
                    <div class="card-body">

                        <table id="example2" class="table table-bordered table-hover table-responsive">
                            <thead>
                            <tr>
                                <th>S.No</th>
                                <th>Course</th>
                                <th>Name </th>
                                <th>Description</th>
                                <th>File</th>
                                <th>Points</th>
                                <th>Published Date</th>
                                <th>Due date</th>
                                <th>Return Count</th>
                                <th>Action</th>
                               

                            </tr>
                            </thead>
                            <tbody>

                            @{
                                int i = 1;
                            }

                            @foreach (var item in ViewBag.data)

                            {
                                <tr>
                                    <td>@i</td>
                                    <td>@item.CourseModel.name</td>
                                    <td>@item.name</td>
                                    <td>@item.description</td>
                                    <td><a href="@item.file">@item.file</a></td>
                                    <td>@item.points</td>
                                    <td>@item.published_date</td>
                                    <td>@item.due_date</td>
                                    <td>0</td>
                                    <td>
                                      
                                    
                                    
                                            <a  asp-route-id="@item.s_no">
                                                <button  type="button" class="btn btn-info">Return Details</button>
                                            </a>
                                       
                                    
                                    </td>
                                    





                               
                                </tr>
                                i++;
                            }
                            </tbody>

                        </table>
                    </div>

                    <!-- /.card-body -->
                </div> 
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
   

    <!-- /.container-fluid -->
</section>