Controllers/TeacherCourseController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using mis_mmc.Models;

namespace mis_mmc.Controllers;

public class TeacherCourseController : Controller
{
    private readonly DataContext _context;

    public TeacherCourseController(DataContext context)
    {
        _context = context;
       
    }
    // GET
    public IActionResult Index(int id)
    {
        var data = _context.CourseModels.Include(f=>f.ProgramModel).Where(x => x.tid.Equals(id)).ToList();
        ViewBag.data = data;
        return View();
    }

    public IActionResult StudentList(int id)
    {
        var sem = (_context.CourseModels.Where(x => x.s_no.Equals(id)).FirstOrDefault()
            .sem_year);
        /*var data = _context.CourseModels.Include(f => f.ProgramModel).Where(x => x.s_no.Equals(id)).FirstOrDefault()
            .ProgramModel.StudentModels.Where(x => x.sem_year.Equals(sem)).ToList();*/
        var pid = _context.CourseModels.Where(x => x.s_no.Equals(id)).FirstOrDefault()
            .pid;
        var data = _context.StudentModels.Where(x => x.pid == pid && x.sem_year == sem).ToList();
        ViewBag.data = data;
        ViewBag.coursename=_context.CourseModels.Where(x => x.s_no.Equals(id)).FirstOrDefault().name;
            
        return View();
    }
}

Views/TeacherCourse/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
    Layout = "_Layout_teacher";

}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>My Courses</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item">
                        <a href="#">Teacher</a>
                    </li>
                    <li class="breadcrumb-item active"> My Courses</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>
<section class="content">
    <div class="container-fluid">

        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                       
                        <form class="search-bar" style="float: left; ">
                            <input type="text" class="form-control" placeholder="Enter keywords" style="float: left">
                            <a href="">
                                <i class="icon-magnifier"></i>
                            </a>
                        </form>
                     
                   
                    </div>
                   


                    <!-- /.card-header -->
                    <div class="card-body">
                       
                        <table id="example2" class="table table-bordered table-hover table-responsive">
                            <thead>
                            <tr>
                                <th>S.No</th>
                                <th>Course name</th>
                                <th>Unique Id</th>
                                <th>Program</th>
                                <th>Semester/Year</th>
                                <th>Description</th>
                                <th>Syllabus</th>
                                <th>Students Count</th>
                                
                                <th>Action</th>
                                
                            </tr>
                            </thead>
                            <tbody>

         @{
                                                         int i = 1;
                                                       }
                                                       @foreach (var item in ViewBag.data)

                                                       {

                                                           <tr>
                                                               <td>@i</td>
                                                               <td>@item.name</td>
                                                               <td>@item.uid</td>
                                                               <td>@item.ProgramModel.name</td>
                                                               <td>@item.sem_year</td>
                                                               <td>@item.description</td>
                                                               <td><a href="@item.file>">@item.file </a></td>
                                                               <td></td>
                                                               




                                                               <td>
                                                                   <a asp-controller="TeacherCourse" asp-action="StudentList" asp-route-id="@item.s_no">
                                                                       <button   type="button" class="btn btn-info">Student List</button>
                                                                   </a>
                                                                  
                                                               </td>
                                                           </tr>
                                                           i++;
                                                       }

                            </tbody>

                        </table>
                    </div>

                    <!-- /.card-body -->
                </div>
                <!-- /.card -->


                <!-- /.card-header -->

                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </div>


    <!-- /.container-fluid -->
</section>

Views/TeacherCourse/StudentList.cshtml
@{
    ViewData["Title"] = "Home Page";
    Layout = "_Layout_Teacher";

}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Students list of @ViewBag.coursename</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item">
                        <a href="#">Teacher</a>
                    </li>
                    <li class="breadcrumb-item active"> Student list </li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>
<section class="content">
    <div class="container-fluid">

        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                       
                        <form class="search-bar" style="float: left; ">
                            <input type="text" class="form-control" placeholder="Enter keywords" style="float: left">
                            <a href="">
                                <i class="icon-magnifier"></i>
                            </a>
                        </form>
                     
                        
                        

                    </div>
                   

-
                    <!-- /.card-header -->
                    <div class="card-body">
                       
                        <table id="example2" class="table table-bordered table-hover table-responsive">
                            <thead>
                            <tr>
                                <th>S.No</th>
                                <th>Unique Id</th>
                                <th>Roll_no</th>
                                <th>Name</th>
                                <th>Email</th>
                                <th>Date of Birth</th>
                                <th>Contact no</th>
                                <th>Address</th>
                                <th>Gender</th>
                                <th>Photo</th>
                                
                                
                                
                            </tr>
                            </thead>
                            <tbody>

  @{
                                   int i = 1;
                               }
                            
                            @foreach (var item in ViewBag.data)

                            {
                                <tr>
                                    <td>@i</td>
                                    
                                    <td>@item.uid</td>
                                    <td>@item.roll_no</td>
                                    <td>@item.name</td>
                                    <td>@item.email</td>
                                    <td>@item.dob</td>
                                    <td>@item.phone</td>
                                    <td>@item.address</td>
                                    <td>@item.gender</td>
                                    
                                    <td><img src="@item.file " style="height: 50px; width : 50px;"></td>
                                    




                                 
                                </tr>
                            }
                            </tbody>

                        </table>
                    </div>

                    <!-- /.card-body -->
                </div>
                <!-- /.card -->


                <!-- /.card-header -->

                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </div>


    <!-- /.container-fluid -->
</section>