Controllers/AdminTeacherController.cs
using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using mis_mmc.Models;

namespace mis_mmc.Controllers;

public class AdminTeacherController : Controller
{
    private readonly DataContext _context;
    private readonly IWebHostEnvironment _webHostEnvironment;
    public AdminTeacherController(DataContext context, IWebHostEnvironment webHostEnvironment)
    {
        _context = context;
        _webHostEnvironment = webHostEnvironment;
    }
    public int Getid ()

    {

        Random r = new Random();
    
        return r.Next(10000,99999);
    
    }
    // GET
    public async Task<string> UploadImage(string folderpath, IFormFile file)
    {
        folderpath += file.FileName;
        string serverFolder = Path.Combine(_webHostEnvironment.WebRootPath, folderpath);
        await file.CopyToAsync(new FileStream(serverFolder, FileMode.Create));
        return "/" + folderpath;
    } // GET
    public IActionResult Index()
    {
        var data = _context.TeacherModels.ToList();
        ViewBag.data = data;
        return View();
    }
    public IActionResult AddTeacher()
    {
        return View();
    }
    
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> AddTeacher(TeacherModel teacherModel, IFormFile file, string password)
    {

        string folder = "file/";
        LoginModel login = new LoginModel()
        {

            email = teacherModel.email,
            password = password,
            role = "Teacher",
            
        };
        TeacherModel teacher = new TeacherModel()
        {
            name = teacherModel.name,
            email = teacherModel.email,
            address = teacherModel.address,
            dob = teacherModel.dob,
            gender = teacherModel.gender,
            phone = teacherModel.phone,
            uid="mmct" + Getid().ToString(), 
            file = await UploadImage(folder, file)

        };
        _context.LoginModels.Add(login);
        _context.TeacherModels.Add(teacher);
        _context.SaveChanges();
        return RedirectToAction("Index");

    }
    
    public IActionResult UpdateTeacher()
    {
        return View();
    }
}

Views/AdminTeacher/AddTeacher.cshtml
@{
    ViewData["Title"] = "Home Page";
    Layout = "_Layout_admin";

}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Add Teacher</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item">
                        <a href="#">Admin</a>
                    </li>
                     <li class="breadcrumb-item "> Teacher</li>
                    <li class="breadcrumb-item active"> Add Teacher</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>
<section class="content">
    <div class="container-fluid">

        <div class="row">
            <div class="col-12">
               <div class="card">
                         <div class="card-body">
                         <div class="card-title">Teacher Regestration Form</div>
                         <hr>
                         <form asp-action="AddTeacher" method="post" enctype="multipart/form-data">
                           
                             
                             <div class="form-group">
                                 <label for="input-3">Full Name</label>
                                 <input type="text" class="form-control" id="input-3" placeholder="Enter Name" name="name" required>
                             </div>
                             <div class="form-group">
                                 <label for="input-4">Email</label>
                                 <input type="email" class="form-control" id="input-4" placeholder="Enter Email" name="email" required>
                             </div>
                             <div class="form-group">
                                 <label for="input-11">Date of Birth</label>
                                 <input type="date" class="form-control" id="input-11" placeholder="Enter dob" name="dob" required>
                             </div>
                             
                             <div class="form-group">
                                 <label for="input-5">File(photo)</label>
                                 <input type="file" class="form-control" id="input-5" name="file">
                             </div>
                             <div class="form-group">
                                 <div class="form-group">
                                     <label for="input-6">Gender</label>
                                     <select class="form-control" id="input-6" placeholder="Enter gender" name="gender" required list="system">
                                         <datalist id="system">
                                             <option > Male </option>
                                             <option > Female</option>
                                         </datalist>
                                     </select>
                                 </div>
                                 <div class="form-group">
                                     <label for="input-7">Phone Number</label>
                                     <input type="number" class="form-control" id="input-7" placeholder="Enter phone number" name="phone" required>
                                 </div>
                                 
                                 <div class="form-group">
                                     <label for="input-8">Address</label>
                                     <input type="text" class="form-control" id="input-8" placeholder="Enter Address" name="address" required>
                                 </div>
                                 
                                 <div class="form-group">
                                     <label for="input-9">Password</label>
                                     <input type="password" class="form-control" id="input-9" placeholder="Enter Password" name="password" required>
                                 </div>
                                 
                              
                                 
                                 
                                 
                                 
                                 
                                 <button type="submit" class="btn btn-light px-5"> Register</button>
                             </div>
                         </form>
                       </div>
                       </div>
                    </div>

                <!-- /.card -->


                <!-- /.card-header -->

                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
   

    <!-- /.container-fluid -->
</section>

Views/AdminTeacher/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
    Layout = "_Layout_admin";

}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Teachers</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item">
                        <a href="#">Admin</a>
                    </li>
                    <li class="breadcrumb-item active"> Teacher</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>
<section class="content">
    <div class="container-fluid">

        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                       
                        <form class="search-bar" style="float: left; ">
                            <input type="text" class="form-control" placeholder="Enter keywords" style="float: left">
                            <a href="">
                                <i class="icon-magnifier"></i>
                            </a>
                        </form>
                        <a style="margin-left: 20px;" asp-action="AddTeacher" asp-controller="AdminTeacher">
                            <button type="button" class="btn btn-primary">Add new</button>
                        </a>

                    </div>
                   


                    <!-- /.card-header -->
                    <div class="card-body">
                       
                        <table id="example2" class="table table-bordered table-hover table-responsive">
                            <thead>
                            <tr>
                                <th>S.No</th>
                                <th>Uid</th>
                                <th>Name</th>
                                <th>Email</th>
                                <td>D.O.B</td>
                                <th>Contact no</th>
                                <th>Address</th>
                                <th>Gender</th>
                                <th>Photo</th>
                                <th>Action</th>
                                
                                
                            </tr>
                            </thead>
                            <tbody>


                            @{
                                                              int i = 1;
                                                          }
                                                       
                                                       @foreach (var item in ViewBag.data)

                                                       {
                                                           <tr>
                                                               <td>@i</td>
                                                               <td>@item.uid</td>
                                                               <td>@item.name</td>
                                                               
                                                               <td>@item.email</td>
                                                               <td> @item.dob</td>
                                                               <td>@item.phone</td>
                                                               <td>@item.address</td>
                                                               <td>@item.gender</td>
                                                               <td><img src="@item.file" style="height: 50px; width : 50px;"></td>





                                                               <td>
                                                                   <a >
                                                                       <button style="width: 70px;" type="button" class="btn btn-info" asp-controller="AdminTeacher" asp-action="UpdateTeacher">Edit</button>
                                                                   </a>
                                                                   <a onclick="return confirm('Are you sure want to delete? ')">
                                                                       <button type="button" class="btn btn-danger">Delete</button>
                                                                   </a>
                                                               </td>

                                                           </tr>
                                                       }
                            </tbody>

                        </table>
                    </div>

                    <!-- /.card-body -->
                </div>
                <!-- /.card -->


                <!-- /.card-header -->

                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </div>


    <!-- /.container-fluid -->
</section>

Views/AdminTeacher/UpdateTeacher.cshtml
@{
    ViewData["Title"] = "Home Page";
    Layout = "_Layout_admin";

}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Update Teacher</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item">
                        <a href="#">Admin</a>
                    </li>
                     <li class="breadcrumb-item "> Teacher</li>
                    <li class="breadcrumb-item active"> Update Teacher</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>
<section class="content">
    <div class="container-fluid">

        <div class="row">
            <div class="col-12">
               <div class="card">
                         <div class="card-body">
                         <div class="card-title">Teacher Update Form</div>
                         <hr>
                         <form>
                           
                             
                             <div class="form-group">
                                 <label for="input-3">Full Name</label>
                                 <input type="text" class="form-control" id="input-3" placeholder="Enter Name" name="name" required>
                             </div>
                             <div class="form-group">
                                 <label for="input-4">Email</label>
                                 <input type="email" class="form-control" id="input-4" placeholder="Enter Email" name="email" required>
                             </div>
                              <div class="form-group">
                                  <label for="input-11">Date of Birth</label>
                                  <input type="date" class="form-control" id="input-11" placeholder="Enter dob" name="dob" required>
                                  </div>
                             <div class="form-group">
                                 <label for="input-5">File(photo)</label>
                                 <input type="file" class="form-control" id="input-5" name="file">
                             </div>
                             <div class="form-group">
                                 <div class="form-group">
                                     <label for="input-6">Gender</label>
                                     <select class="form-control" id="input-6" placeholder="Enter gender" name="gender" required list="system">
                                         <datalist id="system">
                                             <option > Male </option>
                                             <option > Female</option>
                                         </datalist>
                                     </select>
                                 </div>
                                 <div class="form-group">
                                     <label for="input-7">Phone Number</label>
                                     <input type="number" class="form-control" id="input-7" placeholder="Enter phone number" name="phone" required>
                                 </div>
                                 
                                 <div class="form-group">
                                     <label for="input-8">Address</label>
                                     <input type="text" class="form-control" id="input-8" placeholder="Enter Address" name="name" required>
                                 </div>
                                 <button type="submit" class="btn btn-light px-5"> Update</button>
                             </div>
                         </form>
                       </div>
                       </div>
                    </div>

                <!-- /.card -->


                <!-- /.card-header -->

                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
   

    <!-- /.container-fluid -->
</section>